2024-10-30 14:56:54,263 INFO Watching for file changes with StatReloader
2024-10-30 14:57:41,837 INFO Watching for file changes with StatReloader
2024-10-30 14:58:32,380 INFO Watching for file changes with StatReloader
2024-10-30 15:01:02,847 INFO /home/jligo/propital_notification_project/notifications/views.py changed, reloading.
2024-10-30 15:01:04,326 INFO Watching for file changes with StatReloader
2024-10-30 15:01:21,344 INFO Watching for file changes with StatReloader
2024-10-30 15:01:47,804 INFO /home/jligo/propital_notification_project/notifications/views.py changed, reloading.
2024-10-30 15:01:49,196 INFO Watching for file changes with StatReloader
2024-10-30 15:04:42,008 INFO /home/jligo/propital_notification_project/notifications/views.py changed, reloading.
2024-10-30 15:04:43,393 INFO Watching for file changes with StatReloader
2024-10-30 15:05:05,862 INFO /home/jligo/propital_notification_project/notifications/views.py changed, reloading.
2024-10-30 15:05:07,216 INFO Watching for file changes with StatReloader
2024-10-30 15:05:08,397 ERROR Internal Server Error: /api/notifications/
Traceback (most recent call last):
  File "/home/jligo/propital-env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jligo/propital-env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jligo/propital-env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/jligo/propital-env/lib/python3.8/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jligo/propital_notification_project/notifications/views.py", line 23, in dispatch
    print(request[0])
TypeError: 'WSGIRequest' object is not subscriptable
2024-10-30 15:07:34,315 INFO /home/jligo/propital_notification_project/notifications/views.py changed, reloading.
2024-10-30 15:07:35,757 INFO Watching for file changes with StatReloader
2024-10-30 15:07:39,628 ERROR Internal Server Error: /api/notifications/
Traceback (most recent call last):
  File "/home/jligo/propital-env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jligo/propital-env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jligo/propital-env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/jligo/propital-env/lib/python3.8/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jligo/propital_notification_project/notifications/views.py", line 23, in dispatch
    print(self.headers)
AttributeError: 'NotificationViewSet' object has no attribute 'headers'
2024-10-30 15:07:55,788 INFO /home/jligo/propital_notification_project/notifications/views.py changed, reloading.
2024-10-30 15:07:57,158 INFO Watching for file changes with StatReloader
2024-10-30 15:08:33,355 WARNING Unauthorized: /api/notifications/
2024-10-30 15:13:00,237 WARNING Unauthorized: /api/notifications/
2024-10-30 15:13:13,224 WARNING Unauthorized: /api/notifications/
2024-10-30 15:14:28,514 WARNING Unauthorized: /api/notifications/
2024-10-30 15:14:31,017 WARNING Unauthorized: /api/notifications/
2024-10-30 15:15:19,534 WARNING Unauthorized: /api/notifications/
2024-10-30 15:15:41,660 WARNING Unauthorized: /api/notifications/
2024-10-30 15:17:33,042 WARNING Unauthorized: /api/notifications/
2024-10-30 15:17:37,975 WARNING Unauthorized: /api/notifications/
2024-10-30 15:17:39,002 WARNING Unauthorized: /api/notifications/
2024-10-30 15:17:39,978 WARNING Unauthorized: /api/notifications/
2024-10-30 15:26:34,295 WARNING Unauthorized: /api/notifications/
2024-10-30 15:26:44,055 WARNING Unauthorized: /api/notifications/
2024-10-30 15:26:45,543 WARNING Unauthorized: /api/notifications/
2024-10-30 15:26:46,553 WARNING Unauthorized: /api/notifications/
2024-10-30 15:27:54,471 WARNING Unauthorized: /api/notifications/
2024-10-30 15:29:02,476 WARNING Unauthorized: /api/notifications/
2024-10-30 15:29:06,906 WARNING Unauthorized: /api/notifications/
2024-10-30 15:29:52,659 WARNING Unauthorized: /api/notifications/
2024-10-30 15:29:58,478 WARNING Unauthorized: /api/notifications/
2024-10-30 15:29:59,612 WARNING Unauthorized: /api/notifications/
2024-10-30 15:30:01,148 WARNING Unauthorized: /api/notifications/
2024-10-30 15:30:20,219 WARNING Unauthorized: /api/notifications/
2024-10-30 15:31:01,254 WARNING Unauthorized: /api/notifications/
2024-10-30 15:31:39,106 WARNING Unauthorized: /api/notifications/
2024-10-30 15:32:55,182 WARNING Unauthorized: /api/notifications/
2024-10-30 15:33:01,259 WARNING Unauthorized: /api/notifications/
2024-10-30 15:33:02,111 WARNING Unauthorized: /api/notifications/
2024-10-30 15:33:03,050 WARNING Unauthorized: /api/notifications/
2024-10-30 15:33:22,089 WARNING Unauthorized: /api/notifications/
2024-10-30 15:33:37,773 WARNING Unauthorized: /api/notifications/
2024-10-30 15:36:07,200 WARNING Unauthorized: /api/notifications/
2024-10-30 15:36:12,578 WARNING Unauthorized: /api/notifications/
2024-10-30 15:36:13,802 WARNING Unauthorized: /api/notifications/
2024-10-30 15:37:57,514 WARNING Unauthorized: /api/notifications/
2024-10-30 15:38:23,087 WARNING Unauthorized: /api/notifications/
2024-10-30 15:38:28,498 WARNING Unauthorized: /api/notifications/
2024-10-30 15:39:02,471 WARNING Unauthorized: /api/notifications/
2024-10-30 15:39:06,329 WARNING Unauthorized: /api/notifications/
2024-10-30 15:39:08,204 WARNING Unauthorized: /api/notifications/
2024-10-30 15:39:20,958 WARNING Unauthorized: /api/notifications/
2024-10-30 15:39:21,939 WARNING Unauthorized: /api/notifications/
2024-10-30 15:45:40,725 WARNING Unauthorized: /api/notifications/
2024-10-30 15:45:44,528 WARNING Unauthorized: /api/notifications/
2024-10-30 15:45:55,471 WARNING Unauthorized: /api/notifications/
2024-10-30 15:52:15,849 WARNING Unauthorized: /api/notifications/
2024-10-30 15:52:45,019 WARNING Unauthorized: /api/notifications/
2024-10-30 15:55:13,281 INFO /home/jligo/propital_notification_project/notifications/views.py changed, reloading.
2024-10-30 15:55:14,694 INFO Watching for file changes with StatReloader
2024-10-30 16:06:10,136 ERROR Internal Server Error: /api/notifications/
Traceback (most recent call last):
  File "/home/jligo/propital-env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2053, in get_prep_value
    return int(value)
  File "/home/jligo/propital-env/lib/python3.8/site-packages/django/contrib/auth/models.py", line 437, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jligo/propital-env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jligo/propital-env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jligo/propital-env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/jligo/propital-env/lib/python3.8/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jligo/propital_notification_project/notifications/views.py", line 23, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/jligo/propital-env/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/jligo/propital-env/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/jligo/propital-env/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/jligo/propital-env/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/jligo/propital-env/lib/python3.8/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/jligo/propital_notification_project/notifications/views.py", line 19, in get_queryset
    return self.queryset.filter(user=user)
  File "/home/jligo/propital-env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/jligo/propital-env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/jligo/propital-env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/jligo/propital-env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/jligo/propital-env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/jligo/propital-env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/jligo/propital-env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/jligo/propital-env/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/jligo/propital-env/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/jligo/propital-env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2055, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x7f51bdc568e0>.
2024-10-30 16:06:10,227 WARNING Not Found: /favicon.ico
2024-10-30 16:07:25,786 INFO /home/jligo/propital_notification_project/notifications/views.py changed, reloading.
2024-10-30 16:07:27,156 INFO Watching for file changes with StatReloader
2024-10-30 16:16:19,336 INFO /home/jligo/propital_notification_project/propital_notification_project/settings.py changed, reloading.
2024-10-30 16:16:20,821 INFO Watching for file changes with StatReloader
2024-10-30 16:16:35,726 INFO /home/jligo/propital_notification_project/propital_notification_project/settings.py changed, reloading.
2024-10-30 16:16:37,167 INFO Watching for file changes with StatReloader
2024-10-30 16:16:53,174 INFO /home/jligo/propital_notification_project/propital_notification_project/settings.py changed, reloading.
2024-10-30 16:16:54,536 INFO Watching for file changes with StatReloader
2024-10-30 16:17:21,122 INFO /home/jligo/propital_notification_project/propital_notification_project/settings.py changed, reloading.
